version: 0.2
phases:
  install:
    commands:
      - cd client && npm install && cd ..
      - cd server && npm install && cd ..
  build:
    commands:
      - echo "Building frontend"
      - cd client && npm run build
      - echo "Frontend build completed"
  post_build:
    commands:
      - aws s3 sync client/build s3://my-mern-frontend456 --delete
